<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>haiilong</Authors>
    <Company>haiilong</Company>
    <Copyright>Copyright (c) haiilong</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/haiilong/SingletonJob</RepositoryUrl>
    <PackageProjectUrl>https://github.com/haiilong/SingletonJob</PackageProjectUrl>
  </PropertyGroup>
</Project>
