using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SingletonJob.SourceGenerator;

/// <summary>
/// Incremental source generator that finds every non-abstract class deriving from
/// <c>SingletonJob.SingletonBackgroundJob</c> in the user's compilation and emits an extension
/// class with an <c>AddSingletonJobs</c> method that registers each one as an
/// <c>IHostedService</c>. Output is trimming- and NativeAOT-safe: no reflection.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SingletonJobGenerator : IIncrementalGenerator
{
    private const string BaseTypeFullName = "SingletonJob.SingletonBackgroundJob";

    // A ServiceDescriptor needs a closed constructible type; an open generic job class would make the
    // generated registration fail to compile. Skip it and tell the user why instead.
    private static readonly DiagnosticDescriptor GenericJobNotRegistered = new(
        id: "SJOB001",
        title: "Generic singleton job cannot be auto-registered",
        messageFormat: "Job class '{0}' is generic. AddSingletonJobs cannot register an open generic type; " +
                       "register a closed non-abstract subclass instead, or register the job manually with " +
                       "services.AddSingleton<IHostedService, {0}>() using concrete type arguments.",
        category: "SingletonJob",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    // Plain record struct (not readonly): positional properties on a readonly record struct are
    // init-only, which needs IsExternalInit and that is unavailable on netstandard2.0.
    private record struct JobCandidate(string FullName, bool IsGeneric);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jobTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetJobTypeOrNull(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => new JobCandidate(t!.ToDisplayString(), t.IsGenericType))
            .Collect();

        context.RegisterSourceOutput(jobTypes, Emit);
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax cls) return false;
        if (cls.BaseList is null || cls.BaseList.Types.Count == 0) return false;

        // Abstract classes can't be hosted services, skip cheaply at the syntax level.
        return cls.Modifiers.All(modifier => modifier.ValueText != "abstract");
    }

    private static INamedTypeSymbol? GetJobTypeOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol) return null;
        if (symbol.IsAbstract) return null;

        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == BaseTypeFullName) return symbol;
        }
        return null;
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<JobCandidate> candidates)
    {
        var all = candidates.Distinct().OrderBy(c => c.FullName, System.StringComparer.Ordinal).ToList();

        foreach (var generic in all.Where(c => c.IsGeneric))
        {
            spc.ReportDiagnostic(Diagnostic.Create(GenericJobNotRegistered, Location.None, generic.FullName));
        }

        var distinct = all.Where(c => !c.IsGeneric).Select(c => c.FullName).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace SingletonJob;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Source-generated, trimming- and AOT-safe registration for every <see cref=\"SingletonBackgroundJob\"/> subclass in the compilation. Emitted as <c>internal</c> so each consuming assembly gets its own copy.</summary>");
        sb.AppendLine("[System.CodeDom.Compiler.GeneratedCode(\"SingletonJob.SourceGenerator\", \"1.0.0\")]");
        sb.AppendLine("internal static class SingletonJobGeneratedRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every concrete <see cref=\"SingletonBackgroundJob\"/> subclass discovered by the source generator");
        sb.AppendLine("    /// as an <see cref=\"IHostedService\"/>. Optionally binds <see cref=\"SingletonJobOptions\"/> from configuration.");
        sb.AppendLine("    /// Trimming- and NativeAOT-safe (no reflection).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static IServiceCollection AddSingletonJobs(this IServiceCollection services, IConfiguration? configuration = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.ConfigureSingletonJobOptions(configuration);");
        foreach (var fullName in distinct)
        {
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<IHostedService, global::{fullName}>());");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("SingletonJobGeneratedRegistration.g.cs", sb.ToString());
    }
}
