using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SingletonJob.SourceGenerator;

/// <summary>
/// Incremental source generator that finds every non-abstract class deriving from
/// <c>SingletonJob.SingletonBackgroundJob</c> in the user's compilation and emits a partial extension
/// class with an <c>AddSingletonJobsGenerated</c> method that registers each one as an
/// <c>IHostedService</c>. Output is trimming- and NativeAOT-safe: no reflection.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SingletonJobGenerator : IIncrementalGenerator
{
    private const string BaseTypeFullName = "SingletonJob.SingletonBackgroundJob";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jobTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateClass(node),
                transform: static (ctx, _) => GetJobTypeOrNull(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!.ToDisplayString())
            .Collect();

        context.RegisterSourceOutput(jobTypes, Emit);
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax cls) return false;
        if (cls.BaseList is null || cls.BaseList.Types.Count == 0) return false;

        // Abstract classes can't be hosted services, skip cheaply at the syntax level.
        return cls.Modifiers.All(modifier => modifier.ValueText != "abstract");
    }

    private static INamedTypeSymbol? GetJobTypeOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol) return null;
        if (symbol.IsAbstract) return null;

        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == BaseTypeFullName) return symbol;
        }
        return null;
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<string> jobTypeFullNames)
    {
        var distinct = jobTypeFullNames.Distinct().OrderBy(s => s, System.StringComparer.Ordinal).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace SingletonJob;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Source-generated, trimming- and AOT-safe registration for every <see cref=\"SingletonBackgroundJob\"/> subclass in the compilation. Emitted as <c>internal</c> so each consuming assembly gets its own copy.</summary>");
        sb.AppendLine("[System.CodeDom.Compiler.GeneratedCode(\"SingletonJob.SourceGenerator\", \"0.1.0\")]");
        sb.AppendLine("internal static class SingletonJobGeneratedRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// AOT-safe alternative to <see cref=\"ServiceCollectionExtensions.AddSingletonJobs\"/>.");
        sb.AppendLine("    /// Registers every concrete <see cref=\"SingletonBackgroundJob\"/> subclass discovered by the source generator");
        sb.AppendLine("    /// as an <see cref=\"IHostedService\"/>. Optionally binds <see cref=\"SingletonJobOptions\"/> from configuration.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static IServiceCollection AddSingletonJobsGenerated(this IServiceCollection services, IConfiguration? configuration = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.ConfigureSingletonJobOptions(configuration);");
        foreach (var fullName in distinct)
        {
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<IHostedService, global::{fullName}>());");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("SingletonJobGeneratedRegistration.g.cs", sb.ToString());
    }
}
